import React from 'react'
import { describe, expect, it, vi } from 'vitest'
import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MarketHealthChart, MarketPriceWidget, MarketWidgetErrorBoundary, SafetyNetDashboard, buildChartPoints, corruptedMarketPayload, healthyMarketPayload, marketScenarios, summarizeMarketScenario, validateMarketPayload, volatileMarketPayload } from './ErrorBoundarySafetyNet.jsx'

describe('Week 10 Assignment 2 Error Boundary Safety Net', () => {
  it('normal case: renders a healthy market widget with a chart', () => { render(<MarketPriceWidget payload={healthyMarketPayload} />); expect(screen.getByText('ACME')).toBeInTheDocument(); expect(screen.getByRole('img', { name: /market price history line chart/i })).toBeInTheDocument(); expect(screen.getByText(/Live feed/i)).toBeInTheDocument() })
  it('normal case: accepts volatile but valid market data', () => { const result = validateMarketPayload(volatileMarketPayload); expect(result.ok).toBe(true); expect(result.problems).toEqual([]) })
  it('normal case: builds chart coordinates for every history value', () => { const points = buildChartPoints(healthyMarketPayload.history); expect(points.split(' ')).toHaveLength(healthyMarketPayload.history.length); expect(points).toContain(',') })
  it('edge case: catches corrupted data and displays fallback UI', () => { render(<MarketWidgetErrorBoundary><MarketPriceWidget payload={corruptedMarketPayload} /></MarketWidgetErrorBoundary>); expect(screen.getByRole('alert')).toBeInTheDocument(); expect(screen.getByText(/Market Price Widget Out of Order/i)).toBeInTheDocument(); expect(screen.getByText(/Corrupted market data/i)).toBeInTheDocument() })
  it('edge case: catches a missing payload without blanking the page', () => { render(<SafetyNetDashboard scenario={marketScenarios.missing} />); expect(screen.getByText(/Dashboard still works/i)).toBeInTheDocument(); expect(screen.getByRole('alert')).toBeInTheDocument() })
  it('edge case: catches an explicit render-time crash and reports it', () => { const onBoundaryError = vi.fn(); render(<SafetyNetDashboard scenario={marketScenarios.thrown} onBoundaryError={onBoundaryError} />); expect(screen.getByRole('alert')).toBeInTheDocument(); expect(screen.getByText(/Third-party market widget crashed/i)).toBeInTheDocument(); expect(onBoundaryError).toHaveBeenCalled() })
  it('edge case: reset button can clear fallback state when the parent supplies safe data afterward', async () => { const user = userEvent.setup(); function ResetHarness() { const [scenario, setScenario] = React.useState(marketScenarios.corrupted); return <MarketWidgetErrorBoundary onReset={() => setScenario(marketScenarios.healthy)}><MarketPriceWidget payload={scenario.payload} /></MarketWidgetErrorBoundary> } render(<ResetHarness />); expect(screen.getByRole('alert')).toBeInTheDocument(); await user.click(screen.getByRole('button', { name: /reset market widget/i })); expect(screen.getByText('ACME')).toBeInTheDocument() })
  it('helper case: scenario summaries distinguish renderable data from boundary fallback data', () => { const healthySummary = summarizeMarketScenario(marketScenarios.healthy); const corruptedSummary = summarizeMarketScenario(marketScenarios.corrupted); expect(healthySummary.shouldRenderWidget).toBe(true); expect(healthySummary.expectedBoundary).toBe(false); expect(corruptedSummary.shouldRenderWidget).toBe(false); expect(corruptedSummary.expectedBoundary).toBe(true) })
  it('normal case: safety chart renders scenario coverage bars', () => { render(<MarketHealthChart />); expect(screen.getByText(/Scenario Coverage/i)).toBeInTheDocument(); expect(screen.getByText(/Normal widget renders/i)).toBeInTheDocument(); expect(screen.getByText(/Boundary fallbacks expected/i)).toBeInTheDocument() })
})
